### ISSUE TITLE
Git version out of date?

### ISSUE THREAD

**Issue by zgelici** [AnthonyOSX/GO-Bot#179]
try to use the latest version, but i get every time: Title = "GO Bot v0.0.2 [BETA]";.

every zip of the release shows:
GO Bot v0.0.2 [BETA]

The master has the same:
https://github.com/AnthonyOSX/GO-Bot/blob/master/go%20bot/Views/MainWindow.xaml.cs

i think the code is not up2date

**Comment by DuIslingr** [comment]
This is why you download from releases and don't bother with the code if you don't know what ur doing.
https://github.com/AnthonyOSX/GO-Bot/releases

**Comment by azakhi** [comment]
But the code actually is not up to date. I think you should check it before being rude @DuIslingr

**Comment by azakhi** [comment]
See #118

**Comment by zgelici** [comment]
I know what i am doing, i know how to program. How do you know that i dont know what i am doing?
Can you tell me that?

**Comment by DuIslingr** [comment]
Because you are clearly an idiot if you have to point out its out of date. the code is currently 0.0.4 as determined by the commits. Basing it to be 0.0.2 just because one file doesn't have the text changed is rather stupid. Its quite obvious at this point that 0.0.5 code has not yet been commited.

**Comment by zgelici** [comment]
@DuIslingr haha i see some 0.0.4 but i think its not all. i think you are stupid.  go fuck u self

**Comment by DuIslingr** [comment]
You clearly cannot even speak proper English either. Just because you have 1 original project that isn't a fork on your repository list does not make you a "pro". Just go home mmmk kid.

**Comment by zgelici** [comment]
@DuIslingr you are right, i can't speak ingelish :) . did i say i am a Pro?

**Comment by zgelici** [comment]
@DuIslingr you think this is my only one account. :)

**Comment by fenixasin** [comment]
As an english speaker, you two are both idiots arguing about bullshit on a forum that has no bearing in the real world.

The author of this code, as from what I can tell by salivating all over it for days.... does not want help, and is coding most of the changes him/herself.

If that were untrue, or he/she wanted your grubby hands to touch his/her baby, they would commit changes and have the source mirrored here as he/she modified it,

Since that is not the case, stop trying to break what he/she is coding.

There, let the Saltiness flow.

**Comment by zgelici** [comment]
You dont helping anyone. i tried to help this project with improving. but i dont want to lose me time on you. dont response to any of my tickets...

**Comment by zgelici** [comment]
@fenixasin you are true, sorry

**Comment by DuIslingr** [comment]
@fenixasin My original response was based on the assumption he was simply just trying to build the bot himself(which people do instead of using releases. which is fine), in which case my response was not really rude to begin with. I simply said if you don't know what you are doing then don't bother. But because of the lash back, I got pissed off. So regarding that I apologize.

**Comment by zgelici** [comment]
@DuIslingr sorry for my response to you
